version: '2'
services:
  cms:
    image: jwilder/whoami
    container_name: cms
    environment:
      - VIRTUAL_HOST=local.cms.dnainfo.com
    networks:
      - dnainfo

networks:
    # Connect all services to the dnainfo network,
    # which needs to exists before this is launched.
    dnainfo:
      external: true

